version: "3.9"

services:
  discovery-server:
    image: my-discovery-server:latest
    credential_spec:
      file: docker-credentials.yml
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTER-WITH-EUREKA: "false"
      EUREKA_CLIENT_FETCH-REGISTRY: "false"
      EUREKA_INSTANCE_PREFER-IP-ADDRESS: "true"
      EUREKA_DASHBOARD_PATH: /dashboard
    networks:
      - my-network

  config-server:
    image: my-config-server:latest
    credential_spec:
      file: docker-credentials.yml
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
    volumes:
      - ./config:/config
    networks:
      - my-network

  api-gateway:
    image: my-api-gateway:latest
    credential_spec:
      file: docker-credentials.yml
    container_name: GatewayService
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - discovery-server
    networks:
      - my-network

  customer-service:
    image: my-customer-service:latest
    credential_spec:
      file: docker-credentials.yml
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - discovery-server
    networks:
      - my-network

  account-service:
    image: my-account-service:latest
    credential_spec:
      file: docker-credentials.yml
    container_name: AccountService
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    depends_on:
      - discovery-server
    volumes:
      - ./data:/data
    networks:
      - my-network

  transaction-service:
    image: my-transaction-service:latest
    credential_spec:
      file: docker-credentials.yml
    container_name: TransactionService
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
    depends_on:
      - discovery-server
    volumes:
      - ./data:/data
    networks:
      - my-network

  h2-database:
    image: oscarfonts/h2
    ports:
      - "9090:9090"
    volumes:
      - ./h2-data:/opt/h2-data
    environment:
      H2_OPTIONS: "-ifNotExists"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
